name = "filbeam-workflows"
main = "lib/transaction-monitor-workflow.js"
compatibility_date = "2025-09-08"
compatibility_flags = ["nodejs_compat"]
upload_source_maps = true

[env.dev.vars]
RPC_URL = "https://api.calibration.node.glif.io/rpc/v0"
