name = "filcdn-terminator"
main = "bin/terminator.js"
compatibility_date = "2025-09-08"
compatibility_flags = ["nodejs_compat"]
logpush = true

[observability]
enabled = true
head_sampling_rate = 1

[[d1_databases]]
binding = "DB"
database_name = "test-db"
database_id = "8cc92155-16f6-426a-b782-2965e0daf100"

[env.dev.vars]
ENVIRONMENT = "dev"
RPC_URL = "https://api.calibration.node.glif.io/"
FILBEAM_CONTRACT_ADDRESS = "0x0000000000000000000000000000000000000000"

[[env.dev.d1_databases]]
binding = "DB"
database_name = "dev-db"
database_id = "8cc92155-16f6-426a-b782-2965e0daf101"

[env.calibration.vars]
ENVIRONMENT = "calibration"
RPC_URL = "https://api.calibration.node.glif.io/"
FILBEAM_CONTRACT_ADDRESS = "0x50aBAe0B3D37A2fA4D3a7f62FbD49F9a566AeB95"

[[env.calibration.d1_databases]]
binding = "DB"
database_name = "filcdn-calibration-db"
database_id = "78f15bbb-391f-4797-9016-a6cb86c0b9b8"

[env.calibration.triggers]
crons = ["*/1 * * * *"]  # Run every minute

[env.mainnet.vars]
ENVIRONMENT = "mainnet"
RPC_URL = "https://api.node.glif.io/"
FILBEAM_CONTRACT_ADDRESS = "0x010ca67040e80c8FdBF679680D09b94e2A9ac6B8"

[[env.mainnet.d1_databases]]
binding = "DB"
database_name = "filcdn-mainnet-db"
database_id = "e8de6418-2cb7-4413-9ba0-a9c8aacf9a66"

[env.mainnet.triggers]
crons = ["*/1 * * * *"]  # Run every minute

[[env.dev.queues.producers]]
queue = "terminator-transaction-queue-dev"
binding = "TRANSACTION_QUEUE"

# queue concurrency has to be set to 1 in order to send
# transactions one at a time and avoid nonce tracking
[[env.dev.queues.consumers]]
queue = "terminator-transaction-queue-dev"
max_concurrency = 1
max_retries = 3
dead_letter_queue = "transaction-dlq"

[[env.mainnet.queues.producers]]
queue = "terminator-transaction-queue-mainnet"
binding = "TRANSACTION_QUEUE"

# queue concurrency has to be set to 1 in order to send
# transactions one at a time and avoid nonce tracking
[[env.mainnet.queues.consumers]]
queue = "terminator-transaction-queue-mainnet"
max_concurrency = 1
max_retries = 3
dead_letter_queue = "transaction-dlq"

[[env.calibration.queues.producers]]
queue = "terminator-transaction-queue-calibration"
binding = "TRANSACTION_QUEUE"

# queue concurrency has to be set to 1 in order to send
# transactions one at a time and avoid nonce tracking
[[env.calibration.queues.consumers]]
queue = "terminator-transaction-queue-calibration"
max_concurrency = 1
max_retries = 3
dead_letter_queue = "transaction-dlq"

[[env.dev.workflows]]
name = "terminator-transaction-monitor-workflow-dev"
binding = "TRANSACTION_MONITOR_WORKFLOW"
class_name = "TransactionMonitorWorkflow"

[[env.calibration.workflows]]
name = "terminator-transaction-monitor-workflow-calibration"
binding = "TRANSACTION_MONITOR_WORKFLOW"
class_name = "TransactionMonitorWorkflow"

[[env.mainnet.workflows]]
name = "terminator-transaction-monitor-workflow-mainnet"
binding = "TRANSACTION_MONITOR_WORKFLOW"
class_name = "TransactionMonitorWorkflow"
